server:
  port: 9001


eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:7001/eureka/


spring:
  thymeleaf:
    mode: LEGACYHTML5
    cache: false